# Generated by Django 2.1.5 on 2019-01-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='university',
            new_name='university_id',
        ),
    ]
