# Generated by Django 2.1.5 on 2019-01-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('index', models.CharField(max_length=6)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')])),
                ('deficit', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_university', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ManyToManyField(to='student.University'),
        ),
        migrations.AddField(
            model_name='department',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Profile'),
        ),
    ]
