# Generated by Django 2.1.5 on 2019-06-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('profile', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('index', models.DecimalField(decimal_places=0, max_digits=999999, unique=True)),
                ('deficit', models.IntegerField(blank=True, default=0)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='university.University')),
            ],
        ),
    ]
