# Generated by Django 2.1.5 on 2019-01-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='name_of_university',
        ),
    ]
