# Generated by Django 2.1.5 on 2019-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.DecimalField(decimal_places=0, max_digits=999999, unique=True),
        ),
    ]
