# Generated by Django 2.1.5 on 2019-01-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190105_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deficit',
            field=models.IntegerField(blank=True, default=0, max_length=1000),
        ),
    ]
