# Generated by Django 2.1.5 on 2019-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
